### ISSUE TITLE
`*` is not symmetric

### ISSUE THREAD

**Issue by quantenzitrone** [Arcticons-Team/Arcticons-Font#18]
![image](https://github.com/Donnnno/Arcticons-Font/assets/74491719/0ff5360c-36ba-4eba-aaa6-e02f0c1e2f85)

is that intentional?

**Comment by Donnnno** [comment]
Good question! I made that one like two years ago, so maybe it's a good time to revisit it :)

**Comment by Donnnno** [comment]
Switched to rotated strokes of 60 degrees

![afbeelding](https://github.com/Arcticons-Team/Arcticons-Font/assets/31142286/07c931c8-41b5-4a3c-91c3-57f9e4160298)

**Comment by quantenzitrone** [comment]
Have you tried making it 5-pointed (72°) instead of 6-pointed (60°)?

**Comment by Donnnno** [comment]
Nope, but I actually prefer the 6 pointed one haha
