### ISSUE TITLE
apk for Android

### ISSUE THREAD

**Issue by Jak2k** [Arcticons-Team/Arcticons-Font#25]
On android, fonts must be in a special package.

**Comment by Donnnno** [comment]
Never heard of an APK font for android, can you give some more details?

**Comment by Jak2k** [comment]
I couldn't find much information on how to create this, but you might open the [apk of Samsung's font](https://www.apkmirror.com/apk/samsung-electronics-co-ltd/foundation-font/foundation-font-2-3-04-0-release/foundation-font-2-3-04-0-android-apk-download/) as zip to see how it's made.

**Comment by Donnnno** [comment]
Never seen anything like that, and I don't have any idea how that would work. It probably doesn't even work on newer android systems.

For now we're sticking to OTF and WOFF 

Some launchers do allow you to change the font tho

**Comment by Jak2k** [comment]
As far as I can tell, this is used in the newest Samsung devices.

**Comment by Donnnno** [comment]
I found out there's an app called zFont that can change system fonts :)

**Comment by Jak2k** [comment]
> I found out there's an app called zFont that can change system fonts :)

Looks like a virus and doesn't work 🤣

**Comment by Donnnno** [comment]
Oof. 
Took a better look at Samsung theming, they have a strict guideline on how to get on their theme store, with applications only every two years: https://developer.samsung.com/galaxy-themes/overview.html

**Comment by Jak2k** [comment]
> * https://github.com/khirendra03/Font-modules
> * https://github.com/Androidacy/FontManager-Module
> 
> Custom ROMs also usually come with quite a few additional fonts. Apps can ship their own fonts as well.
> 
> Not as universal but options certainly exist
> 
> Also zFont used to be Open Source as well with some commits towards the end that I'll leave uncommented.

Is there a known way to add fonts via adb/shizuku?

**Comment by Donnnno** [comment]
Closing this because it's a bit out of scope for a font.
